version: "3.5"
services:

  dbt:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./env/common.env
      - ./env/oracle.env
    volumes:
      - .:/usr/app
      - ./profiles.yml:/root/.dbt/profiles.yml
    working_dir: /usr/app
    ports:
      - "9000:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: dtr.its.utexas.edu/ebit/oracle:19.3.0-ee
    env_file:
      - ./env/oracle.env
    volumes:
        - ./oradata:/opt/oracle/oradata
        - ./newuser.sh:/opt/oracle/scripts/startup/newuser.sh
    ports:
      - "1521:1521"
      - "5500:5500"

networks:
  default:
    name: debug-net