#!/bin/bash

DBUSER=${DBT_SCHEMA}
DBPASS=${DBT_PASSWORD_LOCAL}

sqlplus SYS/${ORACLE_PWD}@${ORACLE_PDB} AS SYSDBA << EOF

whenever sqlerror exit sql.sqlcode;

CREATE USER "$DBUSER" IDENTIFIED BY "$DBPASS"
  PROFILE "DEFAULT"
  DEFAULT TABLESPACE "USERS"
  TEMPORARY TABLESPACE "TEMP"
  ACCOUNT UNLOCK;

GRANT UNLIMITED TABLESPACE TO "$DBUSER" WITH ADMIN OPTION;

-- run and test Django projects
GRANT CREATE PROCEDURE TO "$DBUSER" WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO "$DBUSER" WITH ADMIN OPTION;
GRANT CREATE SESSION TO "$DBUSER" WITH ADMIN OPTION;
GRANT CREATE TABLE TO "$DBUSER" WITH ADMIN OPTION;
GRANT CREATE TABLESPACE TO "$DBUSER";
GRANT CREATE TRIGGER TO "$DBUSER" WITH ADMIN OPTION;
GRANT CREATE USER TO "$DBUSER";
GRANT CREATE VIEW TO "$DBUSER" WITH ADMIN OPTION;
GRANT DROP USER TO "$DBUSER";
GRANT DROP TABLESPACE TO "$DBUSER";

exit;
EOF
